name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/**.md'
      - '.github/**'

jobs:
  publish:
    name: Publish the app
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Publish
      run: |
        dotnet restore
        dotnet publish -c release -r linux-x64 -p:PublishDir="$GITHUB_WORKSPACE/bin/release/linux-x64"
        dotnet publish -c release -r win-x64 -p:PublishDir="$GITHUB_WORKSPACE/bin/release/win-x64"
        dotnet publish -c release -r osx-x64 -p:PublishDir="$GITHUB_WORKSPACE/bin/release/osx-x64"
      
    - name: Install Zip
      uses: montudor/action-zip@v1
      
    - name: Create Zip
      run: |
        zip -qq -r linux-x64.zip linux-x64/ASF* linux-x64/config.json
        zip -qq -r win-x64.zip win-x64/ASF* win-x64/config.json
        zip -qq -r osx-x64.zip osx-x64/ASF* osx-x64/config.json
      working-directory: bin/release
        
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: bin/release/*.zip
